
name: kibana install & then Uninstall
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update_packages:
    runs-on: centos:latest
    environment: test
    env: # Or as an environment variable
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Uninstall the old packages
        run: |
          echo $SSH_KEY >> ssh_file
          chmod 400 ssh_file
          chmod +x ./uninstall.sh
          ssh -i "ssh_file" root@54.144.78.186 'bash -s' < ./uninstall.sh
      # - name: Installing new packages
      #   run: |
      #     ssh root@54.144.78.186 'bash -s' < myapp/install.sh
